=== tecnologie-web/tecnologie-web/schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- applicazione del modello tende alla veneziana -->   
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
  targetNamespace="http://www.monti.it"
  xmlns="http://www.monti.it"
  elementFormDefault="qualified">
      
   <xsd:element name="dati" type="Tdati" />
      
   <xsd:complexType name="Tdati">
      <xsd:sequence>
        <xsd:element name="iscritti" type="Tiscritti"/>
        <xsd:element name="prodotti" type="Tprodotti"/>
        <xsd:element name="prenotazioni" type="Tprenotazioni"/> 
      </xsd:sequence>
   </xsd:complexType>
         
   <xsd:complexType name="Tiscritti">
      <xsd:sequence>
         <xsd:element name="utente" type="Tutente" maxOccurs="unbuonded" />
      </xsd:sequence>
   </xsd:complexType>
   
   <xsd:complexType name="Tutente">
      <xsd:sequence>
         <xsd:element name="username" type="xsd:ID" />
         <xsd:element name="password" type="xsd:string" />
         <xsd:element name="nome" type="xsd:string" />
         <xsd:element name="cognome" type="xsd:string" />
         <xsd:element name="email" type="xsd:string" minOccurs="0"/>
         <xsd:element name="telefono" type="xsd:integer" />
      </xsd:sequence>
   </xsd:complexType>

   <xsd:complexType name="Tprodotti">
      <xsd:sequence>
         <xsd:element name="vino" type="Tvino" maxOccurs="unbounded"/>
      </xsd:sequence>
   </xsd:complexType>
   <!--
   <etichetta>
	<tipologia> (bianco|rosso|rosato)
	<categoria> (dolce|secco)
	<stato> (frizzante|fermo|spumante)
	<immagine>
	<categoria>
	<uve>
	<provenienza>
	<produzione>
	<altitudine>
	<terreno>
	<densita` piante>
	<periodo di raccolta>
	<vinificazione e afinamento>
	<gradazione alcolica>
	<colore>
	<note di degustazione>
	<abbinamenti gastronomici>
	<temperatura di servizio> -->
   <xsd:complexType name="Tvino">
      <xsd:sequence>
         <xsd:element name="etichetta" type="xsd:ID"/>
         <xsd:element name="immagine" type="xsd:anyURI"/>
         <xsd:element name="tipologia" type="Ttipologia"/>
         <xsd:element name="categoria" type="Tcategoria"/>
         <xsd:element name="stato" type="Tstato"/>
         <xsd:element name="colore" type="xsd:string"/>
         <xsd:element name="uve" type="xsd:string"/>
         <xsd:element name="provenienza" type="xsd:string"/>
         <xsd:element name="produzione" type="Tproduzione"/>
         <xsd:element name="altitudine" type="Taltitudine"/>
         <xsd:element name="terreno" type="xsd:string"/>
         <xsd:element name="densita_p" type="xsd:string"/>
         <xsd:element name="periodoraccolta" type="xsd:string"/>
         <xsd:element name="vinificazione" type="xsd:string"/>
         <xsd:element name="gradazione" type="Tgradazione"/>
         <xsd:element name="degustazione" type="xsd:string"/>
         <xsd:element name="abbinamenti" type="xsd:string"/>
         <xsd:element name="temperatura" type="xsd:string"/>
         <xsd:element name="prezzo" type="Tprezzo"/>
         
      </xsd:sequence>
   </xsd:complexType>
   
   <xsd:complexType name="Ttipologia">
      <
   </xsd:complexType>
   
   <xsd:complexType name="Tprezzo">
      <xsd:simpleContent>
         <xsd:extension base="xsd:decimal">
            <xsd:attribute name="valuta" type="xsd:string" use="required"/>
         </xsd:extension>
      </xsd:simpleContent>
   </xsd:complexType>   
   
   <xsd:complexType name="Tprenotazioni">
      <xsd:sequence>
         <xsd:element name="commissione" type="Tcommissione" maxOccurs="unbounded" />          
      </xsd:sequence>
   </xsd:complexType>
   
   <xsd:complexType name="Tcommissione">
      <xsd:sequence>
         <xsd:element name="cliente" type="xsd:string"/>
            <xsd:sequence minOccurs="1" maxOccurs="unbounded">
               <xsd:element name="ordine" type="xsd:string"/>
               <xsd:element name="quantita" type="xsd:integer"/>
            </xsd:sequence>
         <xsd:element name="data" type="xsd:date"/>
         <xsd:element name="evaso" type="xsd:boolean" default="false"/>
      </xsd:sequence>
      </xsd:complexType>
</xsd:schema>

=== tecnologie-web/tecnologie-web/cgi-bin/registrazione/data.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--?xml-stylesheet type="text/xsl" href="catalogo.xsl"?-->
<data xmlns="http://www.monti.it" xmlns:xsd="http://www.w3.org/2001/XMLSchema-instance" xsd:schemaLocation="http://www.monti.it schema.xsd">
	<iscritti>
		<utente>
			<username>Riki</username>
			<password>password</password>
			<nome>Riccardo</nome>
			<cognome>De Stefani</cognome>
			<email>riccardo.destefani@gmail.com</email>
			<telefono>3485281914</telefono>
		</utente>
		<utente>
			<username>Ale</username>
			<password>password</password>
			<nome>Alessandro</nome>
			<cognome>Cornaglia</cognome>
			<email>ale.corny@gmail.com</email>
			<telefono>3485281915</telefono>
		</utente>
		<utente>
			<username>Catte</username>
			<password>password</password>
			<nome>Giacomo</nome>
			<cognome>Cattelan</cognome>
			<email>giacomo.cattelan@gmail.com</email>
			<telefono>3485281916</telefono>
		</utente>
	</iscritti>
	<prodotti>
		<vino>
			<etichetta>Fior d'arancio</etichetta>
         <immagine>images/prodotti/fiordarancio.png</immagine>
			<categoria>Bianco</categoria>
			<stato>Frizzante</stato>
			<colore>Colore giallo paglierino.....</colore>
         <prezzo valuta="euro">20.36</prezzo>
		</vino>
		<vino>
			<etichetta>Barbera</etichetta>
         <immagine>images/prodotti/fiordarancio.png</immagine>
			<categoria>Rosso</categoria>
			<stato>Fermo</stato>
			<colore>Colore rosso intenso.....</colore>
         <prezzo valuta="euro">20.25</prezzo>
		</vino>
	</prodotti>
</data>

=== tecnologie-web/tecnologie-web/data/db.xml
<!- versione del file xml aggiornata al cinque marzo-->
<!- questa Ã¨ da prendere come la versione ufficiale -->
<?xml version="1.0" encoding="UTF-8" ?>
<?xml-stylesheet type="text/xsl" href="catalogo.xsl"?>
<dati xmlns="http://www.monti.it"
xmlns:xsd="http://www.w3.org/2001/XMLSchema-instance"
xsd:schemaLocation="http://www.cantinabenato.it schema.xsd">
   <iscritti>
		<utente>
			<username>Riki</username>
			<password>password</password>
			<nome>Riccardo</nome>
			<cognome>De Stefani</cognome>
			<email>riccardo.destefani@gmail.com</email>
			<telefono>3485281914</telefono>
		</utente>
		<utente>
			<username>Ale</username>
			<password>password</password>
			<nome>Alessandro</nome>
			<cognome>Cornaglia</cognome>
			<email>ale.corny@gmail.com</email>
			<telefono>3485281915</telefono>
		</utente>
		<utente>
			<username>Catte</username>
			<password>password</password>
			<nome>Giacomo</nome>
			<cognome>Cattelan</cognome>
			<email>giacomo.cattelan@gmail.com</email>
			<telefono>3485281916</telefono>
		</utente>
	</iscritti>
   <prodotti>
      <vino>
      </vino>
   </prodotti>
   
</dati>
